name: Deploy Automático para AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectando no servidor e atualizando a API
        uses: appleboy/ssh-action@v1.0.3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DATABASE_URL,DIRECT_URL
          script: |
            # 1. Carrega o NVM para que os comandos npm, node e pm2 funcionem via SSH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 2. Instala a dependência libatomic exigida pelo Node no Amazon Linux
            # sudo dnf install -y libatomic

            # Instala o pm2 globalmente para gerenciar a aplicação Node.js
            npm install -g pm2

            # 3. Lógica para Clonar ou Atualizar (Pull)
            REPO_DIR="/home/ec2-user/net-api"
            REPO_URL="https://github.com/wesleygomesc6/net-api.git"

            if [ -d "$REPO_DIR" ]; then
              echo "Diretorio encontrado. Atualizando os arquivos..."
              cd $REPO_DIR
              git pull origin master
            else
              echo "Diretorio nao encontrado. Clonando o repositorio..."
              cd /home/ec2-user
              git clone $REPO_URL net-api
              cd net-api
            fi

            # 4. Instala dependências e recria o arquivo .env
            npm install

            echo "DATABASE_URL=$DATABASE_URL" > .env
            echo "DIRECT_URL=$DIRECT_URL" >> .env

            # 5. Faz o build da aplicação
            npm run build

            # 6. Usa o arquivo pm2 para iniciar ou atualizar a API
            pm2 startOrRestart pm2.config.js --env production

            # 7. Salva o estado do PM2
            pm2 save
